# Linkspector configuration file
dirs:
  - ./docs

# Use .gitignore rules to exclude files
useGitIgnore: true

# Check only modified files in Git
modifiedFilesOnly: false

# Ignore patterns - URLs to skip during link checking
ignorePatterns:
  - pattern: "^https://github.com/polkadot-cloud/polkadot-staking-dashboard/compare/v"
  - pattern: "^https://img\\.shields\\.io/badge/"
  - pattern: "^https://github\\.com/polkadot-cloud/polkadot-staking-dashboard/actions/workflows/"

# HTTP headers for specific URLs that require them  
httpHeaders:
  - url:
      - "https://github.com/"
      - "https://guides.github.com/"
      - "https://help.github.com/"
      - "https://docs.github.com/"
    headers:
      Accept-Encoding: "zstd, br, gzip, deflate"

# Status codes that should be considered as "alive" links
aliveStatusCodes:
  - 200
  - 201
  - 202
  - 204

# Follow redirects by default
followRedirects: true
