packages:
  - packages/*
allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  node-hid: true
  usb: true
onlyBuiltDependencies:
  - bufferutil
  - esbuild
  - keccak
  - node-hid
  - sharp
  - utf-8-validate
  - unrs-resolver
  - usb
