// Copyright 2025 @polkadot-cloud/polkadot-staking-dashboard authors & contributors
// SPDX-License-Identifier: GPL-3.0-only

// Map error details to specific translation keys
export const TxErrorKeyMap: Record<string, string> = {
  missing_signer: 'errors.technicalErrorMissingSigner',
  invalid_signer: 'errors.technicalErrorMissingSigner',
  signer_timeout: 'errors.technicalErrorGeneralTimeout',
  signer_error: 'errors.technicalErrorMissingSigner',
  network_timeout: 'errors.technicalErrorNetworkTimeout',
  network_disconnected: 'errors.technicalErrorNetworkDisconnected',
  network_unreachable: 'errors.technicalErrorNetworkUnreachable',
  network_error: 'errors.technicalErrorNetworkDisconnected',
  invalid_nonce: 'errors.technicalErrorInvalidNonce',
  invalid_fee: 'errors.technicalErrorInvalidFee',
  invalid_call: 'errors.technicalErrorInvalidCall',
  invalid_parameters: 'errors.technicalErrorInvalidCall',
  device_locked: 'errors.technicalErrorDeviceLocked',
  device_busy: 'errors.technicalErrorDeviceBusy',
  device_disconnected: 'errors.technicalErrorDeviceDisconnected',
  app_not_open: 'errors.technicalErrorAppNotOpen',
  hardware_error: 'errors.technicalErrorDeviceDisconnected',
  wc_session_disconnected: 'errors.technicalErrorWcSessionDisconnected',
  wc_timeout: 'errors.technicalErrorWcTimeout',
  wallet_connect_error: 'errors.technicalErrorWcSessionDisconnected',
  qr_scan_error: 'errors.technicalErrorQrScanError',
  qr_invalid: 'errors.technicalErrorQrInvalid',
  vault_error: 'errors.technicalErrorQrScanError',
  runtime_incompatible: 'errors.technicalErrorRuntimeIncompatible',
  runtime_unsupported: 'errors.technicalErrorRuntimeUnsupported',
  runtime_error: 'errors.technicalErrorRuntimeIncompatible',
  general_timeout: 'errors.technicalErrorGeneralTimeout',
  permission_denied: 'errors.technicalErrorPermissionDenied',
  rate_limited: 'errors.technicalErrorRateLimited',
  unknown_technical: 'errors.technicalErrorUnknown',
  // Pool-specific errors
  pool_full: 'errors.poolErrorFull',
  pool_blocked: 'errors.poolErrorBlocked',
  pool_destroying: 'errors.poolErrorDestroying',
  pool_invalid_state: 'errors.poolErrorInvalidState',
  pool_error: 'errors.poolErrorInvalidState',
  // Staking-specific errors
  staking_error_min_bond: 'errors.stakingErrorMinBond',
  staking_error_max_nominations: 'errors.stakingErrorMaxNominations',
  staking_error_era_constraint: 'errors.stakingErrorEraConstraint',
  staking_error: 'errors.stakingErrorMinBond',
  // Commission errors
  commission_error_exceeds_max: 'errors.commissionErrorExceedsMax',
  commission_error_exceeds_global: 'errors.commissionErrorExceedsGlobal',
  commission_error_change_rate: 'errors.commissionErrorChangeRate',
  commission_error_invalid_payee: 'errors.commissionErrorInvalidPayee',
  commission_error: 'errors.commissionErrorExceedsMax',
  // Balance errors
  balance_error_locked: 'errors.balanceErrorLocked',
  balance_error_reserve_required: 'errors.balanceErrorReserveRequired',
  balance_error_fee_calculation: 'errors.balanceErrorFeeCalculation',
  balance_error: 'errors.balanceErrorReserveRequired',
  // Validation errors
  validation_error_address_format: 'errors.validationErrorAddressFormat',
  validation_error_metadata_too_long: 'errors.validationErrorMetadataTooLong',
  validation_error_parameter_range: 'errors.validationErrorParameterRange',
  validation_error_invalid_pool_id: 'errors.validationErrorInvalidPoolId',
  validation_error_invalid_validator: 'errors.validationErrorInvalidValidator',
  validation_error: 'errors.validationErrorParameterRange',
}
