// Copyright 2025 @polkadot-cloud/polkadot-staking-dashboard authors & contributors
// SPDX-License-Identifier: GPL-3.0-only

// Map error details to specific translation keys
export const TxErrorKeyMap: Record<string, string> = {
  missing_signer: 'technicalErrorMissingSigner',
  invalid_signer: 'technicalErrorMissingSigner',
  signer_timeout: 'technicalErrorGeneralTimeout',
  signer_error: 'technicalErrorMissingSigner',
  network_timeout: 'technicalErrorNetworkTimeout',
  network_disconnected: 'technicalErrorNetworkDisconnected',
  network_unreachable: 'technicalErrorNetworkUnreachable',
  network_error: 'technicalErrorNetworkDisconnected',
  invalid_nonce: 'technicalErrorInvalidNonce',
  invalid_fee: 'technicalErrorInvalidFee',
  invalid_call: 'technicalErrorInvalidCall',
  invalid_parameters: 'technicalErrorInvalidCall',
  device_locked: 'technicalErrorDeviceLocked',
  device_busy: 'technicalErrorDeviceBusy',
  device_disconnected: 'technicalErrorDeviceDisconnected',
  app_not_open: 'technicalErrorAppNotOpen',
  hardware_error: 'technicalErrorDeviceDisconnected',
  wc_session_disconnected: 'technicalErrorWcSessionDisconnected',
  wc_timeout: 'technicalErrorWcTimeout',
  wallet_connect_error: 'technicalErrorWcSessionDisconnected',
  qr_scan_error: 'technicalErrorQrScanError',
  qr_invalid: 'technicalErrorQrInvalid',
  vault_error: 'technicalErrorQrScanError',
  runtime_incompatible: 'technicalErrorRuntimeIncompatible',
  runtime_unsupported: 'technicalErrorRuntimeUnsupported',
  runtime_error: 'technicalErrorRuntimeIncompatible',
  general_timeout: 'technicalErrorGeneralTimeout',
  permission_denied: 'technicalErrorPermissionDenied',
  rate_limited: 'technicalErrorRateLimited',
  unknown_technical: 'technicalErrorUnknown',
  // Pool-specific errors
  pool_full: 'poolErrorFull',
  pool_blocked: 'poolErrorBlocked',
  pool_destroying: 'poolErrorDestroying',
  pool_invalid_state: 'poolErrorInvalidState',
  pool_error: 'poolErrorInvalidState',
  // Staking-specific errors
  staking_error_min_bond: 'stakingErrorMinBond',
  staking_error_max_nominations: 'stakingErrorMaxNominations',
  staking_error_era_constraint: 'stakingErrorEraConstraint',
  staking_error: 'stakingErrorMinBond',
  // Commission errors
  commission_error_exceeds_max: 'commissionErrorExceedsMax',
  commission_error_exceeds_global: 'commissionErrorExceedsGlobal',
  commission_error_change_rate: 'commissionErrorChangeRate',
  commission_error_invalid_payee: 'commissionErrorInvalidPayee',
  commission_error: 'commissionErrorExceedsMax',
  // Balance errors
  balance_error_locked: 'balanceErrorLocked',
  balance_error_reserve_required: 'balanceErrorReserveRequired',
  balance_error_fee_calculation: 'balanceErrorFeeCalculation',
  balance_error: 'balanceErrorReserveRequired',
  // Validation errors
  validation_error_address_format: 'validationErrorAddressFormat',
  validation_error_metadata_too_long: 'validationErrorMetadataTooLong',
  validation_error_parameter_range: 'validationErrorParameterRange',
  validation_error_invalid_pool_id: 'validationErrorInvalidPoolId',
  validation_error_invalid_validator: 'validationErrorInvalidValidator',
  validation_error: 'validationErrorParameterRange',
}
