# .github/workflows/update-rpc-config.yml
name: 'Update RPC Config'

on:
  push:
    branches: [main]
  schedule:
    - cron: '*/5 * * * *'

concurrency:
  group: update-rpc-config
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.7.1
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Compile check-rpc script
        working-directory: packages/rpc-config
        run: pnpm compile

      - name: Run RPC check
        working-directory: packages/rpc-config
        run: node dist/check-rpc.js

      - name: Exit if no changes
        run: |
          git diff --exit-code packages/rpc-config/src/_generated/index.json || exit 0

      - name: Configure git
        run: |
          git config user.name  "rossbulat"
          git config user.email "ross@jkrb.io"

      - name: Create or update Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore(rpc-config): Update RPC status'
          branch: update/rpc-config
          title: 'chore(rpc-config): Update RPC status'
          body: |
            This PR was generated automatically by a scheduled workflow.
          labels: automated

      - name: Merge Pull Request
        run: gh pr merge ""${{ steps.create_pr.outputs.pull-request-number }}"" --squash --delete-branch --admin
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
